# Basic set up for gradle package manager
version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
  - package-ecosystem: "gradle"
    directory: "/"
    schedule:
      interval: "daily"
  - package-ecosystem: "gradle"
    directory: "/ecs-logging-access/"
    schedule:
      interval: "daily"
  - package-ecosystem: "gradle"
    directory: "/ecs-logging-app/"
    schedule:
      interval: "daily"
  - package-ecosystem: "gradle"
    directory: "/ecs-logging-async/"
    schedule:
      interval: "daily"
  - package-ecosystem: "gradle"
    directory: "/ecs-logging-audit/"
    schedule:
      interval: "daily"
  - package-ecosystem: "gradle"
    directory: "/ecs-logging-base/"
    schedule:
      interval: "daily"
  - package-ecosystem: "gradle"
    directory: "/ecs-logging-kafka/"
    schedule:
      interval: "daily"
  - package-ecosystem: "gradle"
    directory: "/gzip-request-filter-starter/"
    schedule:
      interval: "daily"
