name: CI - Main
on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v1
        with:
          java-version: 11
      - name: Unit Tests
        uses: eskatos/gradle-command-action@v1.3.2
        with:
          arguments: test
      #- name: Codacy Publish
      #  uses: codacy/codacy-coverage-reporter-action@master
      #  with:
      #    project-token: ${{ secrets.CODACY_TOKEN }}

