name: CI - Main
on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4.0.0
        with:
          java-version: 17
          distribution: adopt
      - name: Unit Tests
        uses: eskatos/gradle-command-action@v2.11.1
        with:
          arguments: test
      - name: Codacy Publish
        uses: codacy/codacy-coverage-reporter-action@master
        with:
          project-token: ${{ secrets.CODACY_TOKEN }}

  javadoc:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main' || contains(github.ref, 'refs/tags/')
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4.0.0
        with:
          java-version: 17
          distribution: adopt
      - name: Generate javadoc
        uses: eskatos/gradle-command-action@v2.11.1
        with:
          arguments: globalJavadoc
      #- name: Upload javadoc
      #  uses: sebastianpopp/ftp-action@releases/v2
      #  with:
      #    host: ${{ secrets.WEBSPACE_HOST }}
      #    user: ${{ secrets.WEBSPACE_USER }}
      #    password: ${{ secrets.WEBSPACE_PASSWORD }}
      #    localDir: "build/javadoc/"
      #    remoteDir: "javadoc/"