name: CI - PR
on:
  - pull_request

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v3.13.0
        with:
          java-version: 17
          distribution: adopt
      - name: Unit Tests
        uses: eskatos/gradle-command-action@v2.9.0
        with:
          arguments: test
      - name: "Upload Test Logs Artifact"
        uses: actions/upload-artifact@v3
        if: failure()
        with:
          name: unit-test-logs
          path: |
            build/reports/tests/
            ecs-logging-access/build/reports/tests/
            ecs-logging-app/build/reports/tests/
            ecs-logging-async/build/reports/tests/
            ecs-logging-audit/build/reports/tests/
            ecs-logging-base/build/reports/tests/
            gzip-request-filter-starter/build/reports/tests/
      - name: Codacy Publish
        uses: codacy/codacy-coverage-reporter-action@master
        if: github.actor != 'dependabot[bot]'
        with:
          project-token: ${{ secrets.CODACY_TOKEN }}

  javadoc:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v3.13.0
        with:
          java-version: 17
          distribution: adopt
      - name: Generate javadoc
        uses: eskatos/gradle-command-action@v2.9.0
        with:
          arguments: globalJavadoc