name: CI - PR
on:
  - pull_request

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v1
        with:
          java-version: 11
      - name: Unit Tests
        uses: eskatos/gradle-command-action@v1.3.2
        with:
          arguments: test
      #- name: Codacy Publish
      #  uses: codacy/codacy-coverage-reporter-action@master
      #  if: github.actor != 'dependabot[bot]'
      #  with:
      #    project-token: ${{ secrets.CODACY_TOKEN }}


